name: "InfraConfig"
description: "Configura la infraestructura para la app (CI/CD)"
runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
